# Generated by Django 4.1.1 on 2024-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_created_news_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['title', 'created']},
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
