# Generated by Django 4.1.1 on 2024-04-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
